spring.application.name=PKM-Backend-JAVA
spring.data.mongodb.uri=mongodb://localhost:27017/PKM
spring.data.mongodb.auto-index-creation=true
spring.data.neo4j.uri=bolt://localhost:7687
spring.data.neo4j.user=neo4j
spring.data.neo4j.password=Neo4jSettings
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
